trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: SonarCloudPrepare@3
  inputs:
    SonarQube: 'SonarQube'
    organization: 'azcertssite'
    scannerMode: 'dotnet'
    dotnetScannerVersion: '10.3.0.120579'
    projectKey: 'rluke420672449_AZCertsSite'
    projectName: 'AZCertsSite'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_21_X64'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '20'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'Azure subscription 1('00000000-0000-0000-0000-000000000000')'
    appType: 'webAppLinux'
    appName: 'AZCertsSite'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'

